/**
 * Sitemap with pagination via generateSitemaps()
 *
 * URL structure (generated by Next.js):
 *   /sitemap.xml          → sitemap index (lists all sub-sitemaps)
 *   /sitemap/0.xml        → static pages + first 1,000 signals
 *   /sitemap/1.xml        → next 1,000 signals
 *   …
 *
 * With 17,700+ live signals this ensures Google can discover all pages.
 * Revalidates every 24 h — new disclosures appear in the next day's build.
 */

import { MetadataRoute } from 'next';
import { createServiceClient } from '@/lib/supabase/server';

export const revalidate = 86400; // 24 h

const SITE_URL = 'https://k-marketinsight.com';
const PAGE_SIZE = 1000;

// ── Static pages (always on page 0) ──────────────────────────────────────────

const staticPages: MetadataRoute.Sitemap = [
  {
    url: SITE_URL,
    lastModified: new Date(),
    changeFrequency: 'daily',
    priority: 1.0,
  },
  {
    url: `${SITE_URL}/datasets`,
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: 0.8,
  },
  {
    url: `${SITE_URL}/api-docs`,
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: 0.8,
  },
  {
    url: `${SITE_URL}/pricing`,
    lastModified: new Date(),
    changeFrequency: 'monthly',
    priority: 0.7,
  },
  {
    url: `${SITE_URL}/korea-earnings-signals`,
    lastModified: new Date(),
    changeFrequency: 'daily',
    priority: 0.9,
  },
  {
    url: `${SITE_URL}/korea-dilution-filings`,
    lastModified: new Date(),
    changeFrequency: 'daily',
    priority: 0.9,
  },
  {
    url: `${SITE_URL}/korea-contract-signals`,
    lastModified: new Date(),
    changeFrequency: 'daily',
    priority: 0.9,
  },
];

// ── Helpers ───────────────────────────────────────────────────────────────────

async function getSignalCount(): Promise<number> {
  try {
    const sb = createServiceClient();
    const { count } = await sb
      .from('disclosure_insights')
      .select('*', { count: 'exact', head: true })
      .eq('is_visible', true)
      .eq('analysis_status', 'completed');
    return count ?? 0;
  } catch {
    return 0;
  }
}

async function fetchSignalPage(
  page: number
): Promise<{ id: string; updated_at: string | null }[]> {
  try {
    const sb = createServiceClient();
    const from = page * PAGE_SIZE;
    const to   = from + PAGE_SIZE - 1;
    const { data } = await sb
      .from('disclosure_insights')
      .select('id, updated_at')
      .eq('is_visible', true)
      .eq('analysis_status', 'completed')
      .order('rcept_dt', { ascending: false })
      .range(from, to);
    return data ?? [];
  } catch {
    return [];
  }
}

// ── generateSitemaps ──────────────────────────────────────────────────────────
// Next.js calls this once to determine how many sub-sitemaps to generate.
// Each { id } maps to one /sitemap/[id].xml file.

export async function generateSitemaps(): Promise<{ id: number }[]> {
  const count = await getSignalCount();
  const pages = Math.max(1, Math.ceil(count / PAGE_SIZE));
  return Array.from({ length: pages }, (_, i) => ({ id: i }));
}

// ── Default export ────────────────────────────────────────────────────────────

export default async function sitemap({
  id,
}: {
  id: number;
}): Promise<MetadataRoute.Sitemap> {
  const signals = await fetchSignalPage(id);

  const signalUrls: MetadataRoute.Sitemap = signals.map((s) => ({
    url: `${SITE_URL}/signal/${s.id}`,
    lastModified: s.updated_at ? new Date(s.updated_at) : new Date(),
    changeFrequency: 'weekly' as const,
    priority: 0.7,
  }));

  // Page 0 also carries all static pages
  if (id === 0) {
    return [...staticPages, ...signalUrls];
  }

  return signalUrls;
}
