import Link from 'next/link';
import type { Metadata } from 'next';
import Footer from '@/components/Footer';
import { EVENT_METHODOLOGY } from '@/lib/config/event-methodology';

const SITE_URL = 'https://k-marketinsight.com';

export const metadata: Metadata = {
  title: 'Scoring Methodology - K-MarketInsight',
  description:
    'How K-MarketInsight evaluates Korean corporate disclosures — rule-based, event-specific signal scores, with AI used only to interpret and summarize filings.',
  alternates: { canonical: `${SITE_URL}/methodology` },
};

export default function MethodologyPage() {
  const events = Object.entries(EVENT_METHODOLOGY);

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-900 to-blue-900">
      {/* Header */}
      <header className="border-b border-gray-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <Link href="/" className="flex items-center space-x-3">
            <div className="w-8 h-8 bg-gradient-to-br from-blue-500 to-blue-600 rounded-lg flex items-center justify-center">
              <span className="text-white font-bold text-lg">K</span>
            </div>
            <h1 className="text-2xl font-bold text-white">K-MarketInsight</h1>
          </Link>
        </div>
      </header>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <h1 className="text-5xl font-bold text-white mb-4">Scoring Methodology</h1>
        <p className="text-gray-400 text-lg mb-12 max-w-2xl">
          Signal scores are generated by event-specific, rule-based methodologies — not by AI.
          AI is used only to interpret raw filings and extract structured data and summaries.
        </p>

        {/* AI vs Score 구분 */}
        <div className="grid sm:grid-cols-2 gap-5 mb-14">
          <div className="bg-gray-800/50 backdrop-blur-sm border border-gray-700 rounded-xl p-6">
            <p className="text-xs font-semibold uppercase tracking-widest text-blue-400 mb-2">What AI Does</p>
            <p className="text-gray-300 text-sm leading-relaxed">
              Reads each DART filing, classifies its event type, extracts key figures, and writes
              a plain-language summary. AI does not decide the score.
            </p>
          </div>
          <div className="bg-gray-800/50 backdrop-blur-sm border border-gray-700 rounded-xl p-6">
            <p className="text-xs font-semibold uppercase tracking-widest text-[#00D4A6] mb-2">What The Score Measures</p>
            <p className="text-gray-300 text-sm leading-relaxed">
              A fixed, event-specific formula applied to the extracted data — e.g. contract size
              relative to revenue, dilution rate, dividend yield change. Same inputs always produce
              the same score.
            </p>
          </div>
        </div>

        {/* 이벤트별 방법론 */}
        <div className="space-y-6">
          <h2 className="text-2xl font-bold text-white">Evaluation Factors by Event Type</h2>
          {events.map(([key, m]) => (
            <div key={key} className="bg-gray-800/50 backdrop-blur-sm border border-gray-700 rounded-xl p-6">
              <h3 className="text-lg font-bold text-white mb-2">{m.title}</h3>
              <p className="text-gray-300 text-sm leading-relaxed mb-4">{m.description}</p>
              <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                {m.factors.map((factor) => (
                  <li
                    key={factor}
                    className="rounded-lg bg-gray-900/60 border border-gray-800 px-3 py-2 text-xs text-gray-300"
                  >
                    {factor}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        <p className="text-xs text-gray-600 mt-10 leading-relaxed">
          Scores are risk-adjusted indicators derived from historical DART filings and are provided
          for informational purposes only — not investment advice.
        </p>

        {/* Back to Home */}
        <div className="mt-12 text-center">
          <Link href="/" className="text-blue-400 hover:text-blue-300 transition-colors">
            ← Back to Home
          </Link>
        </div>
      </div>

      <Footer />
    </div>
  );
}
